[ 2023/04/05] refactor/BbajiSpotViewControllerMVVMRefactor >> SpotVC MVVM 리팩토링
OFFTORIVER/BJGG pull request #194
Opened 2023-04-05 13:12 UTC by jeong-hyeonHwang

## 작업사항
**`BbajiSpotViewController`의 비즈니스 로직을 MVC -> MVVM으로 전환**

**1. 비즈니스 로직부 관리를 위한 ViewModel 추가**
- **`BbajiSpotViewController`와 관련된 컴포넌트는 `SpotViewModel`에 의해 관리됩니다.**
**전체 코드**
```swift
// SpotViewModel.swift
protocol OutputOnlyViewModelType {
    associatedtype Output
    
    func transform() async -> Output?
}

final class SpotViewModel: OutputOnlyViewModelType {
    var controlStatus: CurrentValueSubject<ControlStatus, Never> = CurrentValueSubject(.hidden)
    var screenSizeStatus: CurrentValueSubject<ScreenSizeStatus, Never> = CurrentValueSubject(.origin)
    var readyToPlay: CurrentValueSubject<PlayerStatus, Never> = CurrentValueSubject(.origin)
    
    let weatherManager: WeatherManager

    struct Output {
        let rainData: AnyPublisher<String, Never>
        let weatherData: AnyPublisher<[WeatherData], Never>
    }
    
    init() {
        weatherManager = WeatherManager()
    }
     
    func transform() async -> Output? {
        let taskResult = Task { () -> Output? in
            do {
                let weatherItems = try await self.weatherManager.request24HWeather(nx: 61, ny: 126).response.body.items
                let weatherSet = Just(weatherItems.request24HourWeatherItem())
                let rainData = Just(weatherItems.requestRainInfoText())
                let rawWeatherData = Just(weatherItems.requestWeatherDataSet(weatherSet.output))
                
                let weatherData = rawWeatherData.output.map({
                    (rawData) -> WeatherData in
                    return WeatherData(time: rawData.time, iconName: rawData.iconName, temp: rawData.temp, probability: rawData.probability)
                })
                
                return Output(rainData: rainData.eraseToAnyPublisher(), weatherData: Just(weatherData).eraseToAnyPublisher())
            } catch {
                
                if let weatherManagerError = error as? WeatherManagerError {
                    switch weatherManagerError {
                    case .networkError(let message):
                        print(message)
                    case .apiError(let message):
                        print(message)
                    }
                } else if let decodingError = error as? DecodingError {
                    switch decodingError {
                    case .dataCorrupted(let context):
                        print(context.codingPath, context.debugDescription, context.underlyingError ?? "", separator: "\n")
                    default:
                        print(decodingError.localizedDescription)
                    }
                } else {
                    print(error.localizedDescription)
                }
            }
            return nil
        }
        return await taskResult.value
    }
    
    func changeScreenSizeStatus() {
        if screenSizeStatus.value == .normal || screenSizeStatus.value == .origin {
            screenSizeStatus.send(.full)
        } else {
            screenSizeStatus.send(.normal)
        }
    }
    
    func changeControlStatus() {
        if controlStatus.value == .hidden {
            controlStatus.send(.exist)
        } else {
            controlStatus.send(.hidden)
        }
    }
    
    func isReadyToPlay(as status: PlayerStatus) {
        readyToPlay.send(status)
    }
}
```
- **`SpotViewModel`은 아래와 같은 일을 수행합니다.**

|Task|Description|
|:---:|:---|
|`func transform() async -> Output?`|WeatherManager로부터 전달받은 Data를 VC 및 View에 전달|
|`controlStatus`|SpotVC 라이브 스트리밍 카메라의 컨트롤 패널 출력 여부를 관측|
|`screenSizeStatus`|SpotVC 라이브 스트리밍 카메라의 전체화면 출력 여부를 관측|
|`playStatus`|SpotVC 라이브 스트리밍 카메라의 영상 출력 가능 여부를 관측|

- **ViewModel의 값들에 의해 호출되는 VC 및 View의 메소드는 `MARK: ViewModel 호출 메소드`와 함께 해당 UI 스크립트 하위에 extension으로 분리했습니다.**
```swift
// ex.LiveMarkView.swift line.72-95
// MARK: ViewModel 호출 메소드
extension LiveMarkView {
    func liveMarkActive(to active: Bool) {
        let currentColor = backgroundColor
        var targetBackgroundColor: UIColor? = currentColor
        var targetLabelColor: UIColor?
        
        if active {
            targetBackgroundColor = UIColor(rgb: 0xE17481)
            targetLabelColor = .white
        } else {
            targetBackgroundColor = .clear
            targetLabelColor = .clear
            liveLabel.textColor = targetLabelColor
        }
        
        UIView.animate(withDuration: 0.7, delay: 0.3, animations: {
            self.backgroundColor = targetBackgroundColor
            self.liveLabel.textColor = targetLabelColor
            self.isHidden = !active
        })
    }

}
```
- **위와 같은 메소드는 `private func bind(viewModel: SpotViewModel)`에 내부에서 호출됩니다.**
```swift
// ex.LiveMarkView.swift line.56-65
private func bind(viewModel: SpotViewModel) {
        viewModel.playStatus.sink { [weak self] status in
            if status == .readyToPlay {
                self?.liveMarkActive(to: true)
            } else {
                self?.liveMarkActive(to: false)
            }
            
        }.store(in: &cancellables)
    }
```

---

**2. Target-Selector 및 Gesture 관련 코드 `Combine` 기반으로 수정**

|Task|Tool|Description|
|:---:|:---:|:---|
|Target-Selector|`CombineCocoa`|`CombineCocoa`를 import하여 publisher를 적용|
|Gesture|Utilities 폴더 하위 `Combine+GestureRecognizer.swift`|Publisher & Subscription을 활용한 클래스를 통해 Combine 기반 코드로 변경|

- **각각의 항목에 대한 예시 코드는 아래와 같습니다**
- **Target-Selector와 Gesture 관련 코드부는 ViewModel의 특정값에 의한 호출이 아닌, button 혹은 view와 같은 컴포넌트에 의해 호출되는 영역이기에 `private func configureAction` 에서 그대로 호출하도록 만들었습니다.**
```swift
// SpotLiveCameraView.swift line.119-127
    private func configureAction() {
        // Target-Selector가 적용되었던 Button의 경우
        reloadButton.tapPublisher.sink { [self] _ in
            viewModel.changePlayStatus(as: .origin)
        }.store(in: &cancellables)
        
        // UITapGestureRecognizer가 적용되었던 View의 경우
        self.gesture().sink { [self] _ in
            viewModel.changeControlStatus()
        }.store(in: &cancellables)
    }
```

## 이슈번호
- #192 

## 특이사항(Optional)
- ⚠️ **extension `UILabel+` 내부의 `enableCopyText` 메소드는 호출 시 Action을 부여하는 Target-Selector 형식을 그대로 유지했습니다.**
- ⚠️ **Approve 이후에도 영상 정상화 이후 UI갱신이 제대로 이루어지는지 재검토 후 Merge될 예정입니다.**

Close #192

2023-04-09 06:17 UTC, JaewoongLee-swift approved these changes
리팩토링을 하니 코드가 더욱 관리하기 유용해지는 것 같습니다!! 고생 많으셨습니다 :)

코멘트 내용들은 모두 수정요청이 아니라 제안드리는 것이니 다음에 논의해보거나 합리적이라 생각되면 수정해주셔도 될것 같습니다.

2023-04-09 06:17 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/BbajiSpotViewController.swift
> +        bind(viewModel: viewModel)
ViewController에서 bind 메소드의 위치는 어디에 존재하는게 좋을까요? 저희가 정의한 configure 메소드는 ViewController의 기본설정을 한다는 개념이라고 생각되는데어서 viewDidLoad에서 호출되는게 맞다고 느껴지는데 bind 메소드같은 경우에는 레퍼런스에 따라 init에서 또는 viewDidLoad에서 호출되는 시기가 각각 다른것 같습니다.  View가 ViewController 내에서 호출이 되고 나서 데이터를 받아야지만 화면을 그릴 수 있다고 하면 viewDidLoad가 맞는것 같고... 함께 고민해보면 좋을것 같습니다!

2023-04-09 06:17 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/UI Component/ScreenSizeControlButton.swift
> +        self.tapPublisher.sink { [self] in
저희가 MVC 패턴일 때 configure 메소드를 정의하였는데 MVVM 패턴으로 리팩토링을 진행하면서 액션들을 viewModel에 전달하는 코드들도 configure에 작성하는게 괜찮을까요? 함께 논의해보면 좋을것 같습니다!

2023-04-09 06:17 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/UI Component/SpotInfoView.swift
> +               UIApplication.shared.canOpenURL(url as URL) {
contactInfoView에서 받은 이벤트는 ViewModel에 전달하고 ViewModel에서 이벤트를 받으면 전화걸기를 수행하도록 하면 어떨까요? View는 이벤트 전달, ViewModel이 액션을 수행 역할에 더 어울릴 것 같아 제안드립니다!

2023-04-09 06:17 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/UI Component/SpotLiveCameraView.swift
> +        reloadButton.tapPublisher.sink { [self] _ in
저희가 MVC 패턴일 때 configure 메소드를 정의하였는데 MVVM 패턴으로 리팩토링을 진행하면서 액션들을 viewModel에 전달하는 코드들도 configure에 작성하는게 괜찮을까요? 함께 논의해보면 좋을것 같습니다! (2)

2023-04-09 06:17 UTC, JaewoongLee-swift commented on BJGG/BJGG/Utilities/Combine+GestureRecognizer.swift
제스처 바인딩을 직접 구현...!! 멋집니다 엘리제!!!!👍👍👍👍

2023-04-10 07:14 UTC, jeong-hyeonHwang commented on BJGG/BJGG/BbajiSpot/UI Component/ScreenSizeControlButton.swift
> +        self.tapPublisher.sink { [self] in
- 코멘트 감사합니다 커리! 이번 `BbajiSpotViewController` 코드 리팩토링 시에 MVC 패턴일 때 논의되었던 `configureAction`을 그대로 사용하되, 메소드를 분리하여 관리했습니다.
- 확실히 `configureAction`이 ViewModel과 연관성을 지니게되면서 `configure` 메소드로 편입하기보다는 ViewModel과 관련된 메소드를 만들어서 따로 관리하는 것도 좋을 것 같습니다. 다만 `bind`와 `configureAction`이 ViewModel과 연관성이 있으나 담당하는 기능이 다르다고 생각되어 기존의 `configure` 메소드 내부에 `configureConstraints`, `configureStyle`과 같은 요소가 있듯이 메소드를 나눌 필요가 있다고 생각됩니다.
- 다음 회의에서 논의가 이루어질 수 있도록 이슈(#196)를 발행했습니다. 감사합니다 :)

- 현재 코드의 `bind`와 `configureAction`의 주요 기능에 대한 설명을 아래에 첨부합니다.

|bind|configreAction|
|:---:|:---:|
|`ViewModel`의 값 sink 결과에 따라 **UI를 갱신**|Action의 결과에 따라 `ViewModel`에 **값을 전달하는 메소드 호출**<br>**버튼이나 화면을 누르는 등의 행위 자체는 ViewController 측에서 호출하나(ex.tapPublisher),<br>이의 결과로 수반되는 값의 변경은 ViewModel의 메소드를 호출한다.**|

```swift
// bind 예시: SpotLiveCameraView.swift line.120-122
        reloadButton.tapPublisher.sink { [self] _ in
            viewModel.changePlayStatus(as: .origin) // Action에 따라 viewModel의 메소드 호출
        }.store(in: &cancellables)
```

```swift
// configureAction 예시: SpotLiveCameraView.swift line.128-130
        viewModel.controlStatus.sink { [self] status in
            status.changeControlStatusView(view: videoPlayerControlView) // ControlStatus의 변경에 따라 UI를 갱신
        }.store(in: &cancellables)
```
|전체 도식|
|:---:|
|[![](https://mermaid.ink/img/pako:eNqrVkrOT0lVslJKy8kvT85ILCpR8AmKyXOMTs7PS8tMLy1KdUwuyczPi1XQ1bVTqAnLTC33BWrIeTN3hsKrDZOAeOOb7gUKr1dOedPW83rynFcbGhTeztjxZtuc1xNW1DhFJ2XmpUD1hnpCFL-Z26LwZk7L26lzcGlzjoapVbBScPb3DfBxDXGNVdJRyk0tyk3MTAE6tzomT0EhRqkkIzU3NUbJCshMSU1LLM0piVGKyasFKk0sLckPrsxLVrIqKSpN1VEqLUhJLEl1yUxML0rMVbJKS8wpTq0FAFVNcJg?type=png)](https://mermaid.live/edit#pako:eNqrVkrOT0lVslJKy8kvT85ILCpR8AmKyXOMTs7PS8tMLy1KdUwuyczPi1XQ1bVTqAnLTC33BWrIeTN3hsKrDZOAeOOb7gUKr1dOedPW83rynFcbGhTeztjxZtuc1xNW1DhFJ2XmpUD1hnpCFL-Z26LwZk7L26lzcGlzjoapVbBScPb3DfBxDXGNVdJRyk0tyk3MTAE6tzomT0EhRqkkIzU3NUbJCshMSU1LLM0piVGKyasFKk0sLckPrsxLVrIqKSpN1VEqLUhJLEl1yUxML0rMVbJKS8wpTq0FAFVNcJg)|

2023-04-10 07:15 UTC, jeong-hyeonHwang commented on BJGG/BJGG/BbajiSpot/UI Component/SpotLiveCameraView.swift
> +        reloadButton.tapPublisher.sink { [self] _ in
- 이슈#196를 발행했습니다! 감사합니다 :)

2023-04-10 07:57 UTC, jeong-hyeonHwang commented on BJGG/BJGG/BbajiSpot/BbajiSpotViewController.swift
> +        bind(viewModel: viewModel)
`UIViewController`에서 `init` 메소드가 뷰의 데이터를 초기화하는 역할을 담당하고 `View-` 이하의 메소드들이 VC 및 View 내부의 컴포넌트에 대한 관리를 한다는 관점에서는 `bind` 메소드는 `init` 내부에 위치하는게 좀 더 맞을 것 같습니다. 또한 현재 ViewModel의 날씨와 관련되 데이터를 불러오는 작업이 Async-Await 및 Task와 같은 Concurrency를 통해 이루어지고 있기 때문에 `viewDidLoad`에서 호출하지 않아도 데이터 전달 - UI갱신까지의 과정이 정상작동하는 것을 확인했습니다. :)
```swift
// 예시 코드 BbajiSpotViewController.swift : bind init부 편입 시
init() {
        super.init(nibName: nil, bundle: nil)
        bind(viewModel: viewModel)
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    private func configure() {
        configureLayout()
        configureStyle()
        configureComponent()
        configureNotification()
        // 기존 bind 메소드의 위치
    }

```

다만 커리가 말씀하셨던 것처럼 레퍼런스마다 사용하는 방법이 다르고, 단순 테스트 결과로 오류가 나지 않을 것이라고 장담할 수 없어 이 부분도 따로 Discuss 이슈(#197)를 발행해두었습니다. 코멘트 감사합니다!
- #197

2023-04-10 08:04 UTC, jeong-hyeonHwang commented on BJGG/BJGG/BbajiSpot/UI Component/SpotInfoView.swift
> +               UIApplication.shared.canOpenURL(url as URL) {
코멘트 감사합니다! ViewMoel의 메소드로 편입하여 기능을 수행할 수 있도록 변경했습니다.
반영 commit: d426f56

**Part.Gesture Handling**
```swift
// SpotInfoView.swift line.107-111
private func configureAction() {
        contactInfoView.gesture().sink { [self] _ in
            viewModel.callBbaji(to: bbajiInfo.getContact())
        }.store(in: &cancellables)
    }
```

**Part.Action Handling**
```swift
// SpotViewModel.swift line.94-100
func callBbaji(to phoneNumberStr: String) {
        let phoneNumber:Int = Int(phoneNumberStr.components(separatedBy: ["-"]).joined()) ?? 01000000000
        if let url = NSURL(string: "tel://0" + "\(phoneNumber)"),
           UIApplication.shared.canOpenURL(url as URL) {
            UIApplication.shared.open(url as URL, options: [:], completionHandler: nil)
        }
    }
```

2023-05-20 09:02 UTC, JaewoongLee-swift requested changes
다시 리뷰 작성하였습니다. 여러가지 방법에 대해 고민해보고 제안해드렸는데 읽어보시고 리뷰 코멘트에 부족한 내용이 보이면 답글 부탁드릴게요!

2023-05-20 09:02 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/BbajiSpotViewController.swift
> +    private var viewModel = SpotViewModel()
viewModel의 선언방식의 변경이 필요해보입니다.

현재 저희 앱에서 ViewController간 데이터 전달 로직이 존재하지 않지만, 차후 업데이트를 통해 빠지업체가 추가된 상태에서 BbajiHomeViewModel을 통해 선택된 빠지업체 데이터를 전달받아야 하므로 선택된 빠지 데이터를 가지는 SpotViewModel을 BbajiSpotViewController에 초기화 시켜줄 수 있도록 외부에서 접근할 수 있는 방법이 필요합니다.

따라서 viewModel을 초기화시킬 수 있는 방식 두가지를 제안합니다.

**- 방식 1 : initializer를 통해 viewModel 초기화**
```swift
// BbajiSpotViewController
private var viewModel: SpotViewModel

init(viewModel: SpotViewModel) {
    self.viewModel = viewModel
}

// BbajiHomeViewController
didSelectItem(indexPath: IndexPath) {
    let bbaji = bbajiArray[indexPath.row]
    let viewModel = SpotViewModel(bbaji: bbaji)
    let viewController = BbajiSpotViewController(viewModel: viewModel)
    navigationController?.pushViewController(viewController, animated: true)
}
```

**- 방식 2 : 강제언래핑과 프로퍼티 접근을 통한 viewModel 초기화**
```swift
// BbajiSpotViewController
var viewModel: SpotViewModel!

// BbajiHomeViewController
didSelectItem(indexPath: IndexPath) {
    let bbaji = bbajiArray[indexPath.row]
    let viewModel = SpotViewModel(bbaji: bbaji)
    let viewController = BbajiSpotViewController(viewModel: viewModel)
    viewController.viewModel = viewModel
    navigationController?.pushViewController(viewController, animated: true)
}
```

**방식 1**과 **방식 2**번의 차이는 편리함과 안정성의 차이라고 생각합니다.
**방식 1**의 경우, ViewController가 viewModel을 `init(viewModel:)`을 통해서만 초기화 시키고 private을 통해 외부에서 viewModel에 대한 접근을 방지해 초기화 이후에 ViewController 내부 viewModel에 대한 접근을 방지할 수 있습니다. 다만, 새로운 initializer를 만들어야 하기 때문에 ViewController 내부에 코드가 추가되어야 합니다.

**방식 2**의 경우, ViewController에 initializer를 위한 추가적인 코드가 필요없어 편리하다는 장점이 있습니다. (필요한 상황이 있을지는 잘 모르겠지만)ViewController 내부의 viewModel에 언제든 접근도 가능합니다. 단, viewModel을 강제언래핑을 통해 선언하였기 때문에 viewModel을 제대로 초기화 시키지 않을 경우나 내부 로직에 문제가 있을 경우 런타임 오류가 발생할 여지가 있습니다. 또한 외부에서 viewModel의 접근이 불필요한 경우이지만 접근제어를 하지 못해 내부 데이터가 손상될 여지가 있습니다.

따라서 저는 코드의 안정성을 위해 **방식 1**을 추천합니다. 추가적으로 제안하거나 더 나은 방식 있다면 코멘트 부탁드리겠습니다.

2023-05-20 09:02 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/BbajiSpotViewController.swift
> +        Task {
View는 UI를 보여주기 위한 로직만 가져야 한다고 생각합니다. `Task`의 경우 비동기 작업을 실행하기 위한 코드블럭을 제공하므로 메인쓰레드에서의 동작이 주로 필요한 ViewController 내부에서 선언되는 것 보다 SpotViewModel 내부에서 선언되어 데이터를 전달하는 것이 더 역할에 어울린다고 생각됩니다.

2023-05-20 09:02 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/BbajiSpotViewController.swift
> +            viewModel.changePlayStatus(as: .origin)
ViewController의 상태를 viewModel에 전달하는 로직이므로 viewModel의 Input을 통해 전달하는 것은 어떨까요?

View가 본인의 상태를 인지하고 viewModel에 그 상태에 대해 전환메소드를 요청하는 것보다, view에서는 현재 상태가 foreground인지, background인지 viewModel에 전달하고, viewModel 내부에서 해당 상태에 대한 처리를 진행하는게 옳다고 생각됩니다. 그렇게 된다면 view에서는 input을 통해 viewModel이 필요로 하는 상태만 전달하는 역할을 하게 되고, viewModel이 그 상태를 어떻게 진행하는 지는 전혀 알 필요가 없게 됩니다.

해당 방식으로 변경이 된다면 기존의 `configureNotification()`의 역할이 사라지고 `bind(viewModel:)`의 코드가 추가될 것 같습니다.

제가 제안하는 방식은 다음과 같습니다.
```swift
bind(viewModel: SpotViewModel) {
    let input = SpotViewModel.Input(
        didEnterBackground: NotificationCenter.default.publisher(for: UIApplication.willEnterForegroundNotification)
        willEnterForeground: NotificationCenter.default.publisher(for: UIApplication.didEnterBackgroundNotification)
        // 그 외 Input들...
    )
    
    let output = viewModel.transform(input)
    // 그 외 output의 sink 메소드들....
}
```

2023-05-20 09:02 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/SpotViewModel.swift
> +    func transform() async -> Output? {
1. `transform()` 내부에서 Task 작업이 완료되어 `Publisher`만 전달한다면, `async` 키워드는 제거되야 할 것 같습니다.
2. `Output`의 옵셔널타입을 return 하는것보다 `Output`  publisher 프로퍼티들이 빈 값을 반환하도록 하면 어떨까요? publisher로 Empty를 사용하면 괜찮을 것 같습니다.

Empty 참고 : https://developer.apple.com/documentation/combine/empty

2023-05-20 09:02 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/SpotViewModel.swift
> +                let weatherData = rawWeatherData.output.map({
각 코드마다 `Just`로 래핑한 이유가 있을까요? `Output(rainData:weatherData:)`에 초기화 시킬 때만 래핑하여도 괜찮지 않을까 싶어 질문드립니다!

2023-05-20 09:02 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/SpotViewModel.swift
> +            return nil
Output을 그대로 리턴하게 된다면 다음과 같이 코드가 변경되지 않을까 싶습니다.

```swift
//completeImmediately에 대해서는 확실하지 않습니다. complete를 보내야 할지 말아야 할지...
let failRainData = Empty<String, Never>(completeImmediately: false).eraseToAnyPublisher()
let failWeatherData = Empty< [WeatherData], Never>(completeImmediately: false).eraseToAnyPublisher()

return Output(rainData: failRainData weatherData: failWeatherData)
```

2023-05-20 09:02 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/SpotViewModel.swift
> +    func changeScreenSizeStatus() {
BbajiSpotViewController에서 제안드린 내용처럼 수정이 된다면 ViewController에서는 해당 메소드를 알 필요가 없어지므로 private으로 변경되면 좋을 것 같습니다.

2023-05-20 09:02 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/SpotViewModel.swift
> +    func changeControlStatus() {
BbajiSpotViewController에서 제안드린 내용처럼 수정이 된다면 ViewController에서는 해당 메소드를 알 필요가 없어지므로 private으로 변경되면 좋을 것 같습니다. 2

2023-05-20 09:02 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/SpotViewModel.swift
> +    func changePlayStatus(as status: PlayStatus) {
BbajiSpotViewController에서 제안드린 내용처럼 수정이 된다면 ViewController에서는 해당 메소드를 알 필요가 없어지므로 private으로 변경되면 좋을 것 같습니다. 3

2023-05-20 09:02 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/UI Component/SpotInfoView.swift
> +        contactInfoView.gesture().sink { [self] _ in
이부분도 Input과 연결되어 있군요!  내부 View에 있는 액션이라 어떻게 처리해야 할지 고민은 되지만 함께 수정된다면 관리하기 좋을 것 같습니다.

2023-05-20 09:02 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/UI Component/SpotLiveCameraView.swift
> +        reloadButton.tapPublisher.sink { [self] _ in
이부분도 Input으로 함께 전달하면 좋을거같아요!

2023-05-20 09:02 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/UI Component/SpotLiveCameraView.swift
> +        self.gesture().sink { [self] _ in
이부분도 Input으로 함께 전달하면 좋을거같아요! 2

2023-05-20 09:02 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/UI Component/SpotLiveCameraView.swift
> +                viewModel.changePlayStatus(as: .readyToPlay)
이부분도 Input으로 함께 전달하면 좋을거같아요! 3

2023-05-20 09:02 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/UI Component/SpotLiveCameraView.swift
> +                viewModel.changePlayStatus(as: .failed)
이부분도 Input으로 함께 전달하면 좋을거같아요! 4

2023-05-20 09:02 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/UI Component/SpotLiveCameraView.swift
> +                viewModel.changePlayStatus(as: .failed)
이부분도 Input으로 함께 전달하면 좋을거같아요! 5

2023-05-20 09:02 UTC, JaewoongLee-swift commented on BJGG/BJGG/Model/BbajiSpot/WeatherData.swift
> +struct WeatherData {
WeatherData... 데이터 관련된 구조체 명에 대해서 고민이 많습니다. 제가 Model부분을 리팩토링하면서 함께 고민해보겠습니다!

2023-05-20 09:02 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/SpotViewModel.swift
> +import CombineCocoa
해당 파일에서 CombineCocoa가 사용되지 않는 것으로 보입니다. 제거해도 괜찮지 않을까요?

2023-06-24 10:40 UTC, jeong-hyeonHwang commented
### MVVM 2차 REFACTOR 요약

피드백 감사합니다 커리! 저번 코드 리뷰 세션과 피드백을 반영하여 코드를 수정해보았습니다.

코멘트를 남겨주셨던 

**1. viewModel의 선언 방식**
**2. VC 및 View 의 ViewModel Binding (bind) 메소드 내부에서의 Data Call 및 Task 처리**
-> (ex. 날씨와 관련된 정보를 VC 의 bind 메소드 내부에서 direct하게 수행)

**3. UI가 아닌 property의 갱신과 관련된 작업이 VC 및 View에서 이루어지는 문제**
**4. ViewModel transform 메소드의 비동기 처리**

위의 네 가지 사항과 더불어 추가적으로 남겨주셨던 코드 스타일링과 관련된 전반적인 코드를 일괄 수정했습니다.

---
**네 가지 사항에 대한 처리는 아래와 같은 형태로 이루어졌습니다.**
|Number|처리 방식|
|:---:|:---|
|**1**|VC 및 View Init 시 함께 init하는 형태로 변경 (제안해주셨던 1번 방식)|
|**2**|데이터 관련 처리 코드 ViewModel로 이전|
|**3**|VC 및 View 내부에서 사용되는 UI 이외의 프로퍼티 ViewModel로 이전|
|**4**|Publisher를 넘기는 형태로 비동기 구문 제거|

---
이번 리팩토링의 목표는
**1. 불필요한 Optional Input 및 Output 값을 최대한 줄이자**
**2. 기존의 TapGesture 및 Selector - Action, NotificationCenter를 통한 사용자 입력(동작) 처리 구문을 ViewModel을 거친 후 처리할 수 있도록 만들자**
이렇게 두 가지를 세워 진행했습니다.

---

목표 달성 진행 과정은 아래와 같습니다.
**ViewModel 세분화**
|BEFORE|AFTER|
|:---:|:---:|
|SpotVC 내부에서 이루어지는  모든 Action 및<br>데이터 처리를 SpotViewModel **단일 ViewModel**로 처리|SpotViewModel이 담당하는 기능을 총 **4개의 ViewModel로 분산**|

**각각의 ViewModel 내부에서는 사용자 입력의 유무 및 데이터 갱신 방법에 따라 Combine 사용 방식이 상이합니다.**
|Case|Description|Example|
|:---:|:---|:---|
|**@Published**|1. 사용자의 Input이 따로 없이 ViewModel의 init 과정에서 direct로 데이터 초기화가 가능한 경우<br>2. playStatus와 같이 여러 Action에 영향을 받아 변화하는 값인 경우|weatherData, rainData (SpotWeatherViewModel)<br> playStatus (SpotLiveCameraViewModel)|
|**Input - transform -> Output**|사용자의 Input(Action)에 따른 결과(Output)가 있는 경우|TapPublisher, Foreground-Background Notification (SpotViewModel)|
|**Input - transform**|사용자의 Input(Action)은 존재하나 그 결과를 VC 및 View에 전달 없이 ViewModel의 메소드만 수행해도 되는 경우|SpotInfoViewModel|

**4개의 ViewModel 이름과 기능**
|Name|Description|
|:---:|:---|
|**SpotWeatherViewModel**|날씨 정보 갱신을 위한 ViewModel|
|**SpotLiveCameraViewModel**|LiveCameraView에서의 재생과 관련된 Action 처리를 위한 ViewModel|
|**SpotViewModel**|Notification Center의 foreground - background 감지 및 LiveCameraView의 사이즈 (Full Screen - Default) 변경과 관련된 값 갱신 및 Action 처리를 위한 ViewModel|
|**SpotInfoViewModel**|추후 HomeVC로부터 전달받는 BbajiInfo를 기반으로 SpotVC UI Component에서 이루어지는 값 갱신 및 Action 처리를 위한 ViewModel|

**ViewController 및 View에서 사용되는 ViewModel은 아래와 같습니다**
<img width="2832" alt="SpotVC_MVVM" src="https://github.com/OFFTORIVER/BJGG/assets/96641477/ac5026f0-6a27-4c99-934a-1743232f79ed">

---

추가적으로 SpotVC의 정보 구성하는 BbajiInfo가 HomeVC로부터 초기화되는 코드가 적용되지 않은 것을 발견하여 BbajiHomeViewController의 코드 일부를 수정했습니다.
- 기존 코드
```swift
// BbajiHomeViewController.swift line.35-38
extension BbajiHomeViewController: BbajiListViewDelegate {
    func pushBbajiSpotViewController() {
        self.navigationController?.pushViewController(BbajiSpotViewController(dataViewModel: SpotWeatherViewModel(), spotViewModel: SpotViewModel()), animated: true)
}
```
- 수정한 코드
```swift
// BbajiHomeViewController.swift line.35-38
func pushBbajiSpotViewController(index: Int) {
        self.navigationController?.pushViewController(BbajiSpotViewController(infoViewModel: SpotInfoViewModel(info: bbajiInfoArray[index]), weatherViewModel: SpotWeatherViewModel(), spotViewModel: SpotViewModel(), liveCameraViewModel: SpotLiveCameraViewModel()), animated: true)
    }
```

2023-06-24 10:45 UTC, jeong-hyeonHwang commented on BJGG/BJGG/BbajiSpot/BbajiSpotViewController.swift
> +        Task {
수정했습니다! 수정본은 `SpotWeatherViewModel`에서 확인하실 수 있습니다 :)

2023-06-24 10:45 UTC, jeong-hyeonHwang commented on BJGG/BJGG/BbajiSpot/BbajiSpotViewController.swift
> +    private var viewModel = SpotViewModel()
제안 감사합니다! 1번 방식으로 일괄 수정 후 super.init의 위치도 init 메소드의 최상단으로 변경했습니다 :)

2023-06-24 10:46 UTC, jeong-hyeonHwang commented on BJGG/BJGG/BbajiSpot/BbajiSpotViewController.swift
> +            viewModel.changePlayStatus(as: .origin)
제안 감사합니다! TapPublisher 및 NotificationCenter 관련 코드를 일괄적으로 ViewModel을 통해 처리하는 형태로 변경 완료했습니다 :) NotiifcationCenter Publisher와 관련된 사항은 `SpotViewModel`에서 확인하실 수 있습니다!

2023-06-24 10:50 UTC, jeong-hyeonHwang commented on BJGG/BJGG/BbajiSpot/SpotViewModel.swift
> +    func transform() async -> Output? {
1. SpotVC 내부에서 사용되는 ViewModel의 transform 메소드는 더 이상 비동기로 처리되지 않게 되었습니다 :)
2. 기존의 단일 ViewModel이 4개로 분할됨에 따라 Output이 있는 ViewModel은 더 이상 Optional 값을 가지지 않게 되었습니다!
다음에 기회가 된다면 Empty도 써보도록 하겠습니다. 피드백 감사합니다 :D 👍

2023-06-24 10:55 UTC, jeong-hyeonHwang commented on BJGG/BJGG/BbajiSpot/SpotViewModel.swift
> +                let weatherData = rawWeatherData.output.map({
메소드 내부에서 데이터를 바로 추출해서 Publisher로 쓰고자함이 아니었을까...추측해봅니다...😇
해당 데이터는 현재 SpotWeatherViewModel에서 @Published를 사용하여 관리되고 있습니다.

2023-06-24 10:56 UTC, jeong-hyeonHwang commented on BJGG/BJGG/BbajiSpot/SpotViewModel.swift
> +    func changeScreenSizeStatus() {
private으로 변경 완료했습니다!

2023-06-24 10:56 UTC, jeong-hyeonHwang commented on BJGG/BJGG/BbajiSpot/SpotViewModel.swift
> +    func changeControlStatus() {
private으로 변경 완료했습니다!

2023-06-24 11:02 UTC, jeong-hyeonHwang commented on BJGG/BJGG/BbajiSpot/UI Component/SpotInfoView.swift
> +        contactInfoView.gesture().sink { [self] _ in
ContactInfoView의 상위 View인 SpotInfoView에서 SpotInfoViewModel의 메소드를 호출하는 형태로 변경되었습니다!

**SpotInfoViewModel**
```swift
//SpotInfoViewModel.swift
final class SpotInfoViewModel: ViewModelType {
    private let bbajiInfo: BbajiInfo
    private var cancellables = Set<AnyCancellable>()
    
    struct Input {
        let contactTapGesture: AnyPublisher<UITapGestureRecognizer, Never>?
    }
    
    func transform(input: Input) {
        input.contactTapGesture?.sink {[weak self] _ in
            self?.openContact()
        }.store(in: &cancellables)
    }
    
    init(info: BbajiInfo) {
        self.bbajiInfo = info
    }
    
    private func openContact() {
        guard let phoneNumber:Int = Int(bbajiInfo.getContact().components(separatedBy: ["-"]).joined()) else { return }
        if let url = NSURL(string: "tel://0" + "\(phoneNumber)"),
           UIApplication.shared.canOpenURL(url as URL) {
            UIApplication.shared.open(url as URL, options: [:], completionHandler: nil)
        }
    }
}
```

**SpotInfoView**
```swift
//SpotInfoView.swift line.107-116
    private func bind(viewModel: SpotInfoViewModel) {
        let tapGesture = UITapGestureRecognizer()
        contactInfoView.addGestureRecognizer(tapGesture)
        
        let input = SpotInfoViewModel.Input(
            contactTapGesture: tapGesture.tapPublisher
        )
        
        viewModel.transform(input: input)
    }
```

2023-06-24 11:03 UTC, jeong-hyeonHwang commented on BJGG/BJGG/BbajiSpot/UI Component/SpotLiveCameraView.swift
> +        self.gesture().sink { [self] _ in
반영했습니다!

2023-06-24 11:04 UTC, jeong-hyeonHwang commented on BJGG/BJGG/BbajiSpot/SpotViewModel.swift
> +import CombineCocoa
매의 눈이시군요👀👀👀 제거했습니다!

2023-06-25 09:08 UTC, JaewoongLee-swift approved these changes
상세한 설명으로 코드 변경점에 있어 이해하기 편리했습니다!

PR 발행된 날짜가 4월 초더군요... 7월이 다되가는 시점인데 정말 고생 많으셨습니다 엘리제 ㅠㅠ

2023-06-26 08:37 UTC, jeong-hyeonHwang commented
감사합니다 커리! 긴 여정이었습니다...🥹 머지하겠습니다 :D

2023-06-26 08:37 UTC, merged