[2023/05/10] feat/availableServiceUI >> 이용가능 서비스 UI 구현
OFFTORIVER/BJGG pull request #201
Opened 2023-05-10 13:45 UTC by jeong-hyeonHwang

## 작업사항
새롭게 추가되는 이용가능 서비스 탭 UI를 구현했습니다.

- 물리 홈버튼이 있는 기종과 없는 기종의 경우에는 `BbajiConstraints.viewInset`에 의해 자동적으로 margin 값이 16 - 20으로 변화하는 UI로 구현했습니다.

|iPhone14 구현 화면 - 전체 서비스|iPhone14 구현 화면 - 일부 서비스|
|:---:|:---:|
|![Simulator Screenshot - iPhone 14 - 2023-05-10 at 22 08 12](https://github.com/OFFTORIVER/BJGG/assets/96641477/25df879e-490c-4384-ad6a-0fc5122a396b)|![Simulator Screenshot - iPhone 14 - 2023-05-10 at 22 08 20](https://github.com/OFFTORIVER/BJGG/assets/96641477/c3509d23-a3e7-4740-912b-488bc1b5bf8f)|

|iPhoneSE(3rd Generation) <br> 구현 화면 - 전체 서비스|iPhoneSE(3rd Generation) <br> 구현 화면 - 일부 서비스|
|:---:|:---:|
|![Simulator Screenshot - iPhone SE (3rd generation) - 2023-05-10 at 22 21 21](https://github.com/OFFTORIVER/BJGG/assets/96641477/5605f43f-0c50-47b8-9ee9-11dab44f6fa5)|![Simulator Screenshot - iPhone SE (3rd generation) - 2023-05-10 at 22 21 34](https://github.com/OFFTORIVER/BJGG/assets/96641477/acd1ab4c-dc82-4f20-b857-09098beb479b)|

## 이슈번호
- #200 

## 특이사항(Optional)
해당 PR에서는 이용가능 서비스의 UI만을 구현했습니다. 업체별 이용가능한 서비스에 관한 결과값은 임시 데이터를 통해 UI를 작성했습니다.
- Data Model 관련 코드: `BbajiServiceInfo.swift`
```swift
enum BbajiServiceInfo: String {
    case lockerRoom
    case barbecue
    case store
    case equipmentRental
    case waterRides
    case dogCompanion
    case buoy
// 추가적인 메소드는 스크립트 참고
```
- 테스트 적용부: `SpotAvailableServiceView.swift`
```swift
// SpotAvailableServiceView.swift line.80-94
func bind() {
        
        // TODO: Networking Result Receive
        let providedServiceInfoList: [BbajiServiceInfo] = [
            BbajiServiceInfo.lockerRoom,
            BbajiServiceInfo.barbecue,
            BbajiServiceInfo.store,
            BbajiServiceInfo.equipmentRental,
            BbajiServiceInfo.waterRides,
            BbajiServiceInfo.dogCompanion,
            BbajiServiceInfo.buoy
        ]
        
        configureComponent(serviceInfoList: providedServiceInfoList)
    }
```

2023-05-28 11:36 UTC, JaewoongLee-swift requested changes
테스트 관련 주석, print문에 대한 코멘트와 몇가지 제안하는 코멘트를 남겼습니다!

테스트/print문 관련 코드는 제거 부탁드리고 제안하는 코멘트는 참고해주시면 될 것 같습니다 :)

2023-05-28 11:36 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/UI Component/AvailableService/ServiceInfoDescriptionView.swift
> +//        backgroundColor = .yellow
테스트용 주석인것 같습니다. 맞다면 지워주세요!

2023-05-28 11:36 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/UI Component/AvailableService/ServiceInfoDescriptionView.swift
> +        [descriptionImageView, descriptionLabel].forEach({
클로저를 대입할 때 축약형을 사용하면 가독성에 좋고 코드작성도 편리하다고 생각되요. 괜찮다면 수정 부탁드려요!

(예시)
```swift
        [descriptionImageView, descriptionLabel].forEach {
            self.addSubview($0)
         }
```

2023-05-28 11:36 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/UI Component/AvailableService/ServiceInfoDescriptionView.swift
> +        descriptionImageView.snp.makeConstraints({ make in
클로저를 대입할 때 축약형을 사용하면 가독성에 좋고 코드작성도 편리하다고 생각되요. 괜찮다면 수정 부탁드려요! 2

2023-05-28 11:36 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/UI Component/AvailableService/ServiceInfoDescriptionView.swift
> +        descriptionLabel.snp.makeConstraints({ make in
클로저를 대입할 때 축약형을 사용하면 가독성에 좋고 코드작성도 편리하다고 생각되요. 괜찮다면 수정 부탁드려요! 3

2023-05-28 11:36 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/UI Component/AvailableService/ServiceInfoDescriptionView.swift
> +            make.top.equalTo(descriptionImageView.snp.bottom).offset(6)
디자인시스템이 적용된 offset 값으로 보입니다! `BbajiConstraints`에 추가해서 사용하면 재사용하기 편리할것 같습니다.

2023-05-28 11:36 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/UI Component/AvailableService/ServiceInfoDescriptionView.swift
> +        print(serviceInfo.rawValue)
디버깅용 코드로 확인됩니다. 맞다면 제거 부탁드릴게요!

2023-05-28 11:36 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/UI Component/AvailableService/SpotAvailableServiceView.swift
> +            if let standardView = standardView {
[제안]
UICollectionView를 사용하지 않고 뷰들을 구성하게 된다면, `standardView`를 사용해 각 사이클마다 레이아웃 간격을 관리해주는것보다 UIStackView를 활용해보면 어떨까요? 뷰 관련 코드를 관리하는데 있어 더 유용할 것 같습니다.

2023-07-09 12:23 UTC, jeong-hyeonHwang commented on BJGG/BJGG/BbajiSpot/UI Component/AvailableService/SpotAvailableServiceView.swift
> +            if let standardView = standardView {
제안 감사합니다! StackView는 생각도 못하고 있었네요..!
기존 코드의 경우 UICollectionView가 아닌 UIView를 왼쪽에서부터 차례대로 Initialize하는 형태로 구현되어 있었으나, 커리가 제안주신대로 UIStackView를 사용하는 형태로 수정했습니다!
참고 커밋: b3f7a77
|구현 화면|
|:---:|
|![Simulator Screenshot - iPhone 14 - 2023-07-09 at 21 17 43](https://github.com/OFFTORIVER/BJGG/assets/96641477/2c1c812c-6721-4a01-b741-040604562259)|
|기존 구현 사항과 차이는 없습니다.|

2023-07-09 12:23 UTC, jeong-hyeonHwang commented on BJGG/BJGG/BbajiSpot/UI Component/AvailableService/ServiceInfoDescriptionView.swift
> +        print(serviceInfo.rawValue)
ac894b9 에서 제거되었습니다! :)

2023-07-09 12:24 UTC, jeong-hyeonHwang commented on BJGG/BJGG/BbajiSpot/UI Component/AvailableService/ServiceInfoDescriptionView.swift
> +//        backgroundColor = .yellow
ac894b9 에서 제거되었습니다! :)

2023-07-09 12:27 UTC, jeong-hyeonHwang commented on BJGG/BJGG/BbajiSpot/UI Component/AvailableService/ServiceInfoDescriptionView.swift
> +        [descriptionImageView, descriptionLabel].forEach({
해당 Constraints를 `iconNameOffset`으로 추가했습니다! icon과 icon의  nameLabel의 경계를 구분짓는다는 의미에서 `iconNameOffset`으로 이름을 지었으나, 더 좋은 이름이 있다면 언제든지 알려주세요! :)
```swift
//Constraints.swift line.14-15
    // icon과 icon 이름 간 간격 constraint
     static let iconNameOffset: CGFloat = 6.0
```
참고 커밋: 9f2c80c

2023-07-09 12:28 UTC, jeong-hyeonHwang commented on BJGG/BJGG/BbajiSpot/UI Component/AvailableService/ServiceInfoDescriptionView.swift
> +        descriptionImageView.snp.makeConstraints({ make in
감사합니다! 555976c 에서 클로저 축약형으로 수정 반영했습니다!

2023-07-09 12:28 UTC, jeong-hyeonHwang commented on BJGG/BJGG/BbajiSpot/UI Component/AvailableService/ServiceInfoDescriptionView.swift
> +        descriptionLabel.snp.makeConstraints({ make in
555976c 에서 클로저 축약형으로 수정 반영되었습니다! :)

2023-07-09 12:29 UTC, jeong-hyeonHwang commented on BJGG/BJGG/BbajiSpot/UI Component/AvailableService/ServiceInfoDescriptionView.swift
> +            make.top.equalTo(descriptionImageView.snp.bottom).offset(6)
해당 Constraints를 `iconNameOffset`으로 추가했습니다! icon과 icon의  nameLabel의 경계를 구분짓는다는 의미에서 `iconNameOffset`으로 이름을 지었으나, 더 좋은 이름이 있다면 언제든지 알려주세요! :)
```swift
//Constraints.swift line.14-15
    // icon과 icon 이름 간 간격 constraint
     static let iconNameOffset: CGFloat = 6.0
```
참고 커밋: 9f2c80c

2023-09-20 11:31 UTC, JaewoongLee-swift approved these changes
PR 올려주신 지가 얼마나 지났는데 이제야 리뷰를 합니다...

고생하셨어요 엘리제!

2023-11-05 05:35 UTC, merged