[2023/07/09] refactor/networkManager >> NetworkManager 리팩토링
OFFTORIVER/BJGG pull request #210
Opened 2023-07-09 15:17 UTC by jeong-hyeonHwang

## 작업사항
GCD를 기반으로 와이파이 및 셀룰러 환경을 체크하는 NetworkManager의 코드를 Concurrency를 사용하는 형태로 수정했습니다.

---

**기존 코드 보완 설명**
- 기존 코드의 경우, 인터넷 환경을 체크하는 결과값을 `NetworkManager`에서 return하게 되는데, 인터넷이 가능한 경웅 대해서만 이를 `SceneDelegate` 내부의 `willConnectTo`에서 처리하도록 하는 코드로 구성되어 있었습니다.
```swift
// NetworkManager.swift 기존코드
    func startMonitoring(window: UIWindow, completion: @escaping () -> Void ){
        let queue = DispatchQueue(label: "NetworkMonitor")

        // pathUpdateHandler: 인터넷 환경이 변화되는 경우, 이를 감지하여 알려주는 역할을 담당
        monitor.pathUpdateHandler = { [weak self] path in
            self?.status = path.status
            self?.isReachableOnCellular = path.isExpensive

            if path.status != .satisfied {
                DispatchQueue.main.async(execute: {
                    let alert = UIAlertController(title: nil, message: "인터넷에 연결되어 있지 않습니다.\n네트워크 연결을 확인하세요.", preferredStyle: .alert)
                    let action = UIAlertAction(title: "재시도", style: .default, handler: { _ in
                        self?.monitor.start(queue: queue)
                    })
                    alert.addAction(action)

                    window.makeKeyAndVisible()
                    window.rootViewController?.present(alert, animated: true, completion: nil)
                })
            } else {
                completion()
            }
        }
        monitor.start(queue: queue)
    }
```
```swift
// SceneDelegate.swift 기존 코드 (willConnectTo 메소드 내부)
    NetworkManager.shared.startMonitoring(window: window) {

            // Splash Screen 관련 코드
            DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 1.0) {
                self.window?.rootViewController = navigationController
                
                // rootVC의 타입에 따라 데이터를 갱신을 위해 호출하는 메소드가 달라지는 것을 처리하기 위한 if문
                if let rootVC = self.window?.rootViewController as? UINavigationController {
                    if rootVC.viewControllers.count == 1 {
                        if let vc = rootVC.viewControllers[0] as? BbajiHomeViewController {
                            vc.viewModel.fetchWeatherNows()
                            return
                        }
                    } else if rootVC.viewControllers.count == 2 {
                        if let vc = rootVC.viewControllers[1] as? BbajiSpotViewController {
                            vc.configureComponent()
                            return
                        }
                    }
                }
            }
```

---

### Refactoring 코드
**1. SceneDelegate 내부 코드 최소화**
- Status 결과에 따른 Alert 출력 etc와 관련된 사항을 NetworkManager가 담당하는 형태로 수정
```swift
// SceneDelegate.swift line.15-32
    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        
        // rootVC 설정 관련 구문 생략

        // Splash Screen 관련 코드
        DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 1.0) {
            self.window?.rootViewController = navigationController
        }
        
        // 인터넷 환경 체크 관련 코드
        NetworkManager.shared.startMonitoring(window: window)
    } 
```
**2. 앱 종료 후 불필요한 리소스 사용 방지를 위한 SceneDelegate - sceneDidDisconnect 메소드 내부 구문 추가**
```swift
// SceneDelegate.swift line.34-36
    func sceneDidDisconnect(_ scene: UIScene) {
        NetworkManager.shared.stopMonitoring()
    }
```
**3. NWPathMonitor Extension 작성**
- `pathUpdateHandler`로부터 인터넷 환경 status를 direct하게 받는 구문을 AsyncStream을 사용하여 NetworkManager 내부의 코드가 간결해질 수 있도록 수정
- NWPathMonitor를 통해 path events를 전달받기 위해선 DispatchQueue가 필요하기 때문에 기존의 PathHandler를 AsyncStream으로 Wrapping하는 형태로 수정
```swift
// NWPathMonitor+.swift
//  https://stackoverflow.com/questions/74221389/use-nwpathmonitor-with-swift-modern-concurrency-asyncstream-vs-gcd-dispatchqu

import Network

extension NWPathMonitor {
    func paths() -> AsyncStream<NWPath> {
        // 반복문
        AsyncStream { continuation in
            pathUpdateHandler = { path in
                // stream에 path를 제공
                continuation.yield(path)
            }
            // iteration 종료 시 실행문
            continuation.onTermination = { [weak self] _ in
                self?.cancel()
            }

            // path가 변화 event를 감지하는 monitoring을 시작
            start(queue: DispatchQueue(label: "NSPathMonitor.paths"))
        }
    }
}
```
**4. NetworkManager 코드 리팩토링**
- 사용되지 않는 property 및 가독성이 낮은 코드 제거
- SceneDelegate에 있던 코드를 메소드화

|Method Name|Description|
|:---:|:---|
|**startMonitoring<br>(window: UIWindow)**|NWPathMonitor를 통해 전달받은 `path.status` 결과에 따라 다른 메소드를 수행하도록 돕는 메소드<br>인터넷 연결 O:  fetchData 호출<br>인터넷 연결 X: showNetworkStatusAlert 호출|
|**stopMonitoring()**|Monitoring 중지|
|**showNetworkStatusAlert<br>(window: UIWindow)**|인터넷 연결이 필요하다는 Alert 출력|
|**fetchData(window: UIWindow)**|날씨 데이터 Fetch 메소드 호출|

## 이슈번호
#209 

## Reference
[Apple Developer Documentation-AsyncStream](https://developer.apple.com/documentation/swift/asyncstream)
[Apple Developer Documentation-NWPathMonitor](https://developer.apple.com/documentation/network/nwpathmonitor)

[[Swift/iOS] 네트워크 감지 방법에 관한 고찰](https://velog.io/@inwoodev/handling-network-connection-swift-iOS)
[[[iOS/Swift] AsyncStream / AsyncThrowingStream](https://ios-daniel-yang.tistory.com/45)
[AsyncStream / AsyncThrowingStream (feat. RxSwift + Concurrency)](https://zeddios.tistory.com/1341)

[Use NWPathMonitor with Swift Modern Concurrency (AsyncStream) vs GCD (DispatchQueue)](https://stackoverflow.com/questions/74221389/use-nwpathmonitor-with-swift-modern-concurrency-asyncstream-vs-gcd-dispatchqu)

Close #209

2023-09-20 12:35 UTC, JaewoongLee-swift requested changes
`NetworkManager`가 갖고 있는 View에 대한 책임 분리에 대해 코멘트 남겼습니다.

확인 부탁드립니다!

2023-09-20 12:35 UTC, JaewoongLee-swift commented on BJGG/BJGG/Extension/NWPathMonitor+.swift
> +    func paths() -> AsyncStream<NWPath> {
크으... AsyncStream을 활용해 멋진 코드가 나왔군요!! 참고링크도 함께 남겨주신 덕에 코드를 이해하기 수월했습니다. 멋져요!!!

2023-09-20 12:35 UTC, JaewoongLee-swift commented on BJGG/BJGG/Network/NetworkManager.swift
> +    func startMonitoring(window: UIWindow) {
네트워크 관련 모듈인 `NetworkManager`에서 View에 해당하는 `UIWindow`를 파라미터로 받는 것은 Model-View간의 의존성을 만들게 된다고 생각됩니다. View에 대한 의존성이 생기니 `NetworkManager`가 본인의 책임인 네트워크 판별을 벗어나 `showNetworkStatusAlert(window:)`, `fetchData(window:)`같은 화면과 관련된 역할을 갖게 된다고 느껴집니다.

`NetworkManager`에서는 네트워크 성공/실패 여부만 체크해 결과를 리턴하고, 그에 대한 결과값을 `SceneDelegate`나, 각 ViewModel 내부에서 사용하도록 하는건 어떨까요?

2023-09-20 12:35 UTC, JaewoongLee-swift commented on BJGG/BJGG/SceneDelegate.swift
> +        NetworkManager.shared.startMonitoring(window: window)
`NetworkManager`에 남긴 코멘트와 함께 코드를 제안드리자면,

 해당 줄에서 `window`를 전달하지 않고 `path.status`을 리턴한다면 `SceneDelegate` 내부에서 전달받아 처리를 해도 괜찮을 듯 합니다. 이렇게 하면 `NetworkManager`는 네트워크 판별의 책임만 가져갈 수 있겠네요!

2023-10-12 08:22 UTC, jeong-hyeonHwang commented
안녕하세요 커리! NetworkManager의 의존성 분리에 관한 코멘트 정말 감사합니다!
커리가 말씀하신대로 기존 코드에서 보였던 NetworkManager - View, Window 간의 의존성 제거를 위해 작업 내용에 대한 설명을 첨부합니다.추가적인 코드 리뷰 및 질문, 수정 요청 사항 남겨주시면 확인하겠습니다! 감사합니다!!! :)

---
### NetworkManager 의존성 분리

**1. NetworkManger View, Window 관련 parameter 제거**
- 기존 코드의 경우 매개변수로 window를 받아 해당 alert를 출력하거나, 각각의 VC에 맞는 fetch 메소드를 호출하는 형태였습니다.
- 변경된 코드에서 NetworkManager는 Monitoring에 대한 결과만을 단순히 리턴하거나, Monitoring을 정지하는 코드로 구성되게 되었습니다.

```swift
// NetworkManager.swift
final class NetworkManager {
    @Published var networkConnectionStatus: NWPath.Status?
    
    static let shared = NetworkManager()
    
    private let monitor = NWPathMonitor()
    
    private init() {
        startMonitoring()
    }
    
    func startMonitoring() {
        Task {
            for await path in monitor.paths() {
                networkConnectionStatus = path.status
            }
        }
    }
    
    func stopMonitoring() {
        monitor.cancel()
    }
}
```
**2. Alert 출력 및 데이터 갱신 메소드 분리**
- 기존의 네트워크 상태 확인 Alert를 출력하는 메소드는 `UIViewController+`로 이동하여 extension 형태로 구성하였습니다.

```swift
// UIViewController+.swift
extension UIViewController {
    func showNetworkStatusAlert() {
        let alert = UIAlertController(title: nil, message: "인터넷에 연결되어 있지 않습니다.\n네트워크 연결을 확인하세요.", preferredStyle: .alert)
        let action = UIAlertAction(title: "확인", style: .default) { _ in
            alert.removeFromParent()
        }
        alert.addAction(action)
        present(alert, animated: true, completion: nil)
    }
    
    func dismissPresentedAlert() {
        if let presentedAlert = presentedViewController as? UIAlertController {
            presentedAlert.dismiss(animated: true)
        }
    }
}
```
- dataFetch와 관련된 메소드는 각각의 ViewContoller에서 NetworkManager의 `networkConnectionStatus` 프로퍼티와의 바인딩 시에 호출하는 구조로 변경되었습니다.
- SceneDelegate가 아닌 ViewController 각각에서 해당 메소드를 호출하는 이유는 단순 Network Monitoring 뿐만이 아니라 Alert 출력이나  데이터 로딩과 같이 뷰의 컨텐츠에 직접적으로 영향을 주는 코드로, SceneDelegate보다 ViewController에 위치해야한다고 판단하여 아래와 같은 형태로 만들었습니다.
**MARK**: Network 환경이 성립하는 경우 각각의 VC에서는 ViewModel로부터 데이터를 로딩하는 메소드를 수행합니다.
```swift
private extension BbajiSpotViewController {
    func bindNetworkStatus() {
        NetworkManager.shared.$networkConnectionStatus
            .receive(on: DispatchQueue.main)
            .sink { [weak self] networkConnectionStatus in
                guard let networkStatus = networkConnectionStatus else { return }
                switch networkStatus {
                case .satisfied:
                    self?.dismissPresentedAlert()
                    self?.weatherViewModel?.receiveBbajiWeatherData() // MARK
                    // BbajiHomeViewController의 경우: self?.viewModel?.fetchWeatherNows()
                case .unsatisfied:
                    self?.showNetworkStatusAlert()
                case .requiresConnection:
                    self?.dismissPresentedAlert()
                @unknown default:
                    fatalError()
                }
            }.store(in: &cancellables)
    }
}
```

---

### 비고
- 기존 네트워크 환경 Alert의 출력 형태와 워딩이 변경되었습니다.

**1. Alert 출력 형태**
- 와이파이 및 셀룰러 데이터가 전부 OFF가 되어있는 경우 Alert를 띄운 후 '재시도(변경 후, 확인)' 버튼 클릭 시 Alert는 다시 출현하지 않습니다.
- NWPathMonitor의 경우 Connection 상태가 변경된 경우, 이를 감지하여 알려주는 구조로, 기존 코드에서는 Monitoring과 관련된 코드를 View 간의 의존성을 높임으로서 재귀적인 호출을 가능하게 만들었으나, 의존성 제거 후 호출이 불가능하게 되었습니다.
- NWPathMonitor에서 새로운 extension을 만들어 지속적으로 상태를 알려주는 메소드를 만들 수는 있지만(예를 들면 타이머 n초마다 status 확인) Combine을 사용해 데이터 fetch가 자동적으로 이루어지도록 만들어둔 현재 코드에서 해당 메소드는 오버 스펙으로 생각되어 구현하지 않았습니다.

**2. Alert 워딩**

|기존 워딩|변경된 워딩|
|:---:|:---:|
|재시도|확인|
- **재시도**의 경우 버튼 Action을 통해 임의로 네트워크 상태를 다시금 받아오는 맥락으로 이해되나, 변경된 코드에서는 해당 기능을 수행하는 코드부가 따로 존재하지 않기 때문에 워딩을 **확인**으로 대체했습니다.

|실행 영상|
|:---:|
|![](https://github.com/OFFTORIVER/BJGG/assets/96641477/9e19bcb3-3bd5-4ada-bf38-54b228b7800f)|

2023-10-12 08:24 UTC, jeong-hyeonHwang commented on BJGG/BJGG/Network/NetworkManager.swift
> +    func startMonitoring(window: UIWindow) {
코멘트 감사합니다! 의존성 분리를 위한 리팩토링을 6eeb82d 에서 진행했습니다. 확인 부탁드립니다 :)

2023-10-12 08:25 UTC, jeong-hyeonHwang commented on BJGG/BJGG/SceneDelegate.swift
> +        NetworkManager.shared.startMonitoring(window: window)
코멘트 감사합니다! 의존성 분리를 위한 리팩토링을 6eeb82d 에서 진행했습니다. 확인 부탁드립니다 :)

2023-10-23 15:54 UTC, JaewoongLee-swift requested changes

2023-10-23 15:54 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiHome/BbajiHomeViewController.swift
> +    func bindNetworkStatus() {
SceneDelegate에서 ViewController로 옮긴것은 좋은 변경점 같습니다!

ViewController(즉, 담당화면)에서 네트워크 감지를 수행하게 된다면, 해당 동작은 ViewModel 안에서 수행되는게 더 책임이 어울리지 않을까요?
ViewModel에서 네트워크 감지를 시작하고, 성공 또는 실패가 일어날 경우 그때 ViewController에 바인딩되어 있는 Publisher를 통해 동작을 하도록 하면 ViewController가 좀 더 View 동작에만 집중할 수 있을 것 같습니다.

2023-10-23 15:54 UTC, JaewoongLee-swift commented on BJGG/BJGG/BbajiSpot/BbajiSpotViewController.swift
> +    func bindNetworkStatus() {
`BbajiHomeViewController` 에서의 코멘트와 동일한 내용입니다.

2023-10-23 15:54 UTC, JaewoongLee-swift commented on BJGG/BJGG/Extension/UIViewController+.swift
> +            alert.removeFromParent()
알러트가 등록되고 사라질 때, removeFromParent()를 꼭 해줘야 하나요?
정말 몰라서 여쭤봅니다!

2023-10-23 15:54 UTC, JaewoongLee-swift commented on BJGG/BJGG/Network/NetworkManager.swift
> +    func startMonitoring() {
`startMonitoring()`의 역할이 확실히 줄어들었군요! 수정 감사합니다 😊

2023-10-29 04:26 UTC, jeong-hyeonHwang commented on BJGG/BJGG/Extension/UIViewController+.swift
> +            alert.removeFromParent()
찾아보니까 AlertController의 경우에는 일회성으로 호출되고 사라지는 UIController라 따로 `removeFromParent`를 사용할 필요가 없다고 합니다...! 따라서 [e0e98cd] 에서 해당 코드부를 삭제했습니다 꼼꼼한 확인 감사합니다 :)

2023-10-29 04:46 UTC, jeong-hyeonHwang commented
안녕하세요 커리! 이번에 남겨주신 코멘트도 확인했습니다!
다시 살펴보니 커리가 말씀하신대로 NetworkManager가 MVVM 패턴에 알맞지 않게 ViewController에서 상태를 감지하고 있는 점을 확인했습니다.
추가적인 리팩토링을 진행하여 아래에 주요 작업 사항에 대한 설명을 첨부합니다. 코멘트 감사합니다! :D

**참고 커밋:** ab30168

### NetworkManager - VC 간의 의존성 분리
**NetworkViewModel 구현**
기존 코드의 경우 ViewController 각각에서 fetch하는 데이터 코드부를 제외한 나머지 코드의 중복을 확인했습니다. 이를 고려하여, 기존에 존재하는 HomeVC, SpotVC에서 개별적으로 사용되던 ViewModel에 네트워크 관련 코드를 삽입하는 것이 아니라 `NetworkViewModel`을 만들어 재사용이 가능하게 만들었습니다. 대략적인 데이터 구조는 아래와 같습니다.
[![](https://mermaid.ink/img/pako:eNpVjrEOgzAMRH8FeYYfYKjU0rEwFKkL6WARA1GDUwVHqAL-vUGoQz3Zp3d3XqB1miCHzrq5HdBLcrsrTuKcm4pkdv5VImNP_plk2WnlQyscM7ViHNeCEqb18qMfhuYyZtqDN1P15yC9Fs3OxFu8szYGK94bIYWR_IhGx3eWXVEgA42kII-rpg6DFQWKt4hiEFd_uIVcfKAUwluj0NVg73GEvEM70fYF1IlPqw?type=png)](https://mermaid.live/edit#pako:eNpVjrEOgzAMRH8FeYYfYKjU0rEwFKkL6WARA1GDUwVHqAL-vUGoQz3Zp3d3XqB1miCHzrq5HdBLcrsrTuKcm4pkdv5VImNP_plk2WnlQyscM7ViHNeCEqb18qMfhuYyZtqDN1P15yC9Fs3OxFu8szYGK94bIYWR_IhGx3eWXVEgA42kII-rpg6DFQWKt4hiEFd_uIVcfKAUwluj0NVg73GEvEM70fYF1IlPqw)

|Property|Type|Description|
|:---:|:---:|:---|
|**networkConnectionStatus**|NWPath.Status|네트워크 관련 상태를 raw한 값으로 NetworkViewModel에 전달|
|**isNetworkConnected**|Bool|NetworkViewModel에서 Bool값으로 정제된 데이터를 각 ViewController에 전달|

### 비고
`NetworkViewModel`의 경우 BbajiHome 뿐만이 아니라 BbajiSpot에서 두루 사용되는 ViewModel로, 기존의 VC 기반 폴더링 구조에 편입하기 어려워 현재 Network 폴더에 위치하고 있습니다. 전반적인 데이터 리팩토링이 끝나면  해당 클래스를 어떻게 관리하면 좋을지와 더불어 폴더링 구조 전환에 대해 논의해보면 좋을 것 같습니다!

2023-10-29 07:09 UTC, JaewoongLee-swift approved these changes
NetworkViewModel은 고민이 조금 되네요...
일단 리팩토링이 오래 진행되고 있는 만큼 머지한 다음 자세한 내용을 나눠봐야 될거같아요.

고생하셨습니다 엘리제! 다음 회의에서 많은 이야기를 나눠보도록 합시다 후후

2023-11-05 04:54 UTC, merged